### PR TITLE
Hi, I want to compare forks at my dinner table. I NEED HELP! Notice me Senpai!

### PR DESCRIPTION
**Pull request by MichaelSmeaton**
It won't let me upload files! ¿Porque? :$#@!

### CODE REVIEW

**Comment by ghost** [comment]
Are you trying to upload your files via browser??

**Comment by MichaelSmeaton** [comment]
I'm using Google Chrome

**Comment by ghost** [comment]
Ah that would be very difficult. 
I suggest you to use Github application like, https://desktop.github.com/
That application will download all files and folders in the https://github.com/ZachChristensen/Theseus-and-the-Minotaur/ to your local directory. 
To upload your files, you just copy and paste the file into that directory. 
The application will recognize the change and upload them for you, and download all changed that were created by other users.

I believe this guide will help you configure it.
https://help.github.com/desktop/guides/getting-started/

**Comment by ghost** [comment]
https://help.github.com/desktop/guides/contributing/adding-and-cloning-repositories/

Clone https://github.com/ZachChristensen/Theseus-and-the-Minotaur/

**Comment by MichaelSmeaton** [comment]
Thank you Github expert, I followed your instructions and I think it worked... 
/ thread

**Pull request closed without merging**
